import { i } from "#scripts/utils";
import { Daw } from "#scripts/types";
import type { AlbumData } from "#scripts/types";


export const albums: {
  [series: string]: AlbumData[]
} = {
  pinned: [
    {
      shard: "singles",
      name: "Singles",
      cover: "sunset.png",
      tracks: [
        {
          shard: "sunset",
          name: "Sunset",
          audio: "sunset.m4a",
          cover: "sunset.png",
          genres: ["electronic"],
          vibes: ["chillout"],
        },
        {
          shard: "sunrise",
          name: "Sunrise",
          audio: "sunrise.m4a",
          cover: undefined,
          genres: ["electronic"],
          vibes: ["chillout"],
        },
      ]
    },
  ],
  gen1: [
    {
      shard: "algo-origins",
      name: "Algorhythm Origins",
      date: "2023 – PRESENT",
      cover: "origins.night.png",
      daw: Daw.GarageBand,
      desc: `Soundtracks created for my rhythm game ${i("Algorhythm")}"!`,
      tracks: [
        {
          shard: "dawn",
          name: "Dawn",
          audio: "dawn.m4a",
          cover: "origins.dawn.png",
          genres: ["electronic"],
          vibes: ["muted", "chill"],
        },
        {
          shard: "day",
          name: "Day",
          audio: "day.m4a",
          cover: "origins.day.png",
          genres: ["electronic"],
          vibes: ["vibrant"],
        },
        {
          feat: true,
          shard: "night",
          name: "Night",
          audio: "night.m4a",
          cover: "origins.night.png",
          genres: ["electronic"],
          vibes: ["vibrant"],
        },
        {
          shard: "yesterday",
          name: "Yesterday",
          audio: "yesterday.m4a",
          cover: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "tomorrow",
          name: "Tomorrow",
          audio: "tomorrow.m4a",
          cover: "origins.tomorrow.png",
          genres: ["electronic"],
          vibes: ["jubilant"],
        },
        {
          shard: "dusk",
          name: "Dusk",
          audio: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
        {
          feat: true,
          shard: "time",
          name: "Time",
          audio: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "twilight",
          name: "Twilight",
          audio: "twilight.m4a",
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
      ],
    },
    {
      shard: "algo-roots",
      name: "Algorhythm Roots",
      date: "2024 – PRESENT",
      cover: undefined,
      daw: Daw.GarageBand,
      desc: `More soundtracks created for my rhythm game ${i("Algorhythm")}!`,
      tracks: [
        {
          shard: "away",
          name: "Away",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "rejuvenate",
          name: "Rejuvenate",
          audio: "rejuvenate.m4a",
          cover: undefined,
          genres: ["electronic"],
          vibes: ["jubilant"],
        },
        {
          shard: "drop",
          name: "Drop",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "rush-reloaded",
          name: "Rush Reloaded",
          audio: "rush-reloaded.m4a",
          cover: undefined,
          genres: ["rhythm", "arcade"],
          vibes: ["intense"],
        },
        {
          shard: "rise",
          name: "Rise",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: ["melodramatic"],
          is_preview: true,
        },
      ],
    },
    {
      shard: "algo-vision",
      name: "Algorhythm Vision",
      date: "2024 – PRESENT",
      cover: "vision.another-dawn.png",
      daw: Daw.GarageBand,
      desc: `New soundtracks created for the revival of my rhythm game ${i("Algorhythm")}.`,
      tracks: [
        {
          shard: "another-dawn",
          name: "Another Dawn",
          audio: "another-dawn.m4a",
          cover: "vision.another-dawn.png",
          genres: ["electronic"],
          vibes: ["epic", "vibrant"],
        },
        {
          shard: "daybreak",
          name: "Daybreak",
          audio: undefined,
          cover: undefined,
          genres: ["electronic"],
          vibes: ["vibrant"],
          is_preview: true,
        },
        {
          shard: "nightfall",
          name: "Nightfall",
          audio: undefined,
          cover: undefined,
          genres: ["electronic"],
          vibes: ["vibrant"],
          is_preview: true,
        },
        {
          shard: "reminiscence",
          name: "Reminiscence",
          audio: "reminiscence.m4a",
          cover: "vision.reminiscence.png",
          genres: ["ambient", "lo-fi"],
          vibes: ["muted"],
        },
        {
          shard: "midnight",
          name: "Midnight",
          audio: undefined,
          cover: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
      ],
    },
    {
      shard: "elysion",
      name: "ELYSION",
      date: "2023 – PRESENT",
      cover: "elysion.ceruleus.png",
      daw: Daw.GarageBand,
      desc: `Experimental soundtracks in a variety of genres.`,
      tracks: [
        {
          shard: "aphenia",
          name: "Aphenia",
          audio: "aphenia.m4a",
          cover: "elysion.aphenia.png",
          genres: ["neurofunk", "ambient"],
          vibes: ["sinister"],
        },
        {
          shard: "ephemerald",
          name: "Ephemerald",
          audio: undefined,
          cover: undefined,
          genres: ["artcore"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "lullacry",
          name: "Lullacry",
          audio: undefined,
          cover: undefined,
          genres: ["lo-fi"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "ceruleus",
          name: "Ceruleus",
          audio: "ceruleus.m4a",
          cover: "elysion.ceruleus.png",
          genres: ["orchestral", "neurofunk"],
          vibes: ["poignant"],
        },
        {
          shard: "archiral",
          name: "Archiral",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "viridian",
          name: "Viridian",
          audio: "viridian.m4a",
          cover: "elysion.viridian.png",
          genres: ["artcore"],
          vibes: ["vibrant"],
        },
        {
          shard: "scars",
          name: "Scars",
          audio: undefined,
          cover: undefined,
          genres: ["hardcore"],
          vibes: ["melodramatic"],
          is_preview: true,
        },
      ],
    },
    {
      shard: "cortex",
      name: "Cortex",
      date: "2024 – PRESENT",
      cover: "cortex.voxel.png",
      daw: Daw.GarageBand,
      desc: `Techy!`,
      tracks: [
        {
          shard: "purity",
          name: "puri:ty",
          audio: undefined,
          cover: undefined,
          genres: ["neurofunk"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "voxel",
          name: "Voxel",
          audio: "voxel.m4a",
          cover: "cortex.voxel.png",
          genres: ["electronic", "complextro", "arcade"],
          vibes: ["bop"],
        },
        {
          shard: "pseudorandom",
          name: "pseudorandom",
          audio: "pseudorandom.m4a",
          cover: "cortex.pseudorandom.png",
          genres: ["wackcore"],
          vibes: ["random"],
        },
        {
          shard: "dactyl",
          name: "Dactyl",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "mem-brain",
          name: "MEM=BRAIN",
          audio: undefined,
          cover: "cortex.mem-brain.png",
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "syntax-error",
          name: "SyntaxError",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "elysion",
          name: "Π0!ZV/Σ",
          audio: "elysion.m4a",
          cover: "cortex.elysion.png",
          genres: [],
          vibes: [],
        },
        {
          shard: "the-algorithm",
          name: "The Algorithm",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
      ],
    },
    {
      shard: "integral",
      name: "Integral",
      date: "2024 – PRESENT",
      daw: Daw.GarageBand,
      desc: "Soundtracks for nontrivial mathematical shenanigans.",
      tracks: [
        {
          shard: "audacious-antiderivative",
          name: "Audacious Antiderivative",
          audio: undefined,
          cover: undefined,
          genres: ["electronic", "polymeter"],
          vibes: ["vibrant"],
          is_preview: true,
        },
        {
          shard: "pathological-constant",
          name: "Pathological Constant",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "isomorphic-surjection",
          name: "Isomorphic Surjection",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "subzero-abstraction",
          name: "Subzero Abstraction",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "luminous-conjecture",
          name: "Luminous Conjecture",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "transverse-erratum",
          name: "Transverse Erratum",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "canonical-destruction",
          name: "Canonical Destruction",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "infinitesimal-ignition",
          name: "Infinitesimal Ignition",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
      ],
    },
    {
      name: "Affinity",
      date: "FUTURE",
      shard: "affinity",
      is_preview: true,
      tracks: [
        "solitude",
        "pinpricks",
        "forest-foliage",
        "close-to-earth",
        "midnight-marauder",
        "night-dweller",
        "droplets",
        "blinded-by-water",
        "cloudjumper",
      ],
    },
    {
      name: "Fidelity",
      date: "FUTURE",
      shard: "fidelity",
      is_preview: true,
      tracks: [
        "our-time",
        "a-place-far-away",
        "whisper",
        "lost-in-your-eyes",
        "intrepid",
        "a-time-long-ago",
        "our-story",
      ],
    },
    {
      name: "Stranded",
      date: "2025 – PRESENT",
      shard: "stranded",
      tracks: [
        "stranded",
        "catastropical",
        "a-journey-across-time",
        "ever-shining",
        "requital",
        "facts_pinned",
        "walkers",
      ],
    },
  ],
  archives: [
    {
      name: "GarageBand Archives",
      date: "2024 – EARLIER",
      shard: "garageband",
      cover: "garageband.jpg",
      daw: Daw.GarageBand,
      desc: `Miscellaneous and ancient creations in GarageBand.`,
      tracks: [
        {
          shard: "let-you-down",
          name: "Let You Down",
          date: "2024 SPRING",
          audio: "let-you-down.m4a",
          vibes: ["chill", "jokes"],
        },
        {
          shard: "canon-in-d-remix",
          name: "Canon in D (remix)",
          date: "2019",
          audio: "canon-in-d-remix.m4a",
          genres: ["orchestral", "electronic"],
        },
        {
          shard: "rush",
          name: "Rush",
          date: "2019",
          audio: "rush.m4a",
          genres: ["bass"],
          vibes: ["experimental"],
        },
        {
          feat: true,
          shard: "base-memories",
          name: "Base Memories",
          date: "2019",
          audio: "base-memories.m4a",
          genres: ["bass"],
          vibes: ["muted", "experimental"],
        },
      ],
    },
    {
      name: "MuseScore Archives",
      date: "2023 – EARLIER",
      shard: "musescore",
      cover: "musescore.png",
      daw: Daw.MuseScore,
      desc: `Piano and orchestral compositions from MuseScore`,
      tracks: [
        {
          shard: "wingless-butterfly",
          name: "The Wingless Fire-Wielding Butterfly Who Waged War Upon the Forest",
          date: "2023 WINTER",
          audio: "wingless-butterfly.mp3",
          genres: ["piano"],
          vibes: ["jokes"],
        },
        {
          shard: "bubble-iris",
          name: "Bubble Iris",
          date: "2023",
          audio: "bubble-iris.mp3",
          cover: "bubble-iris.jpg",
          genres: ["orchestral", "cinematic"],
          vibes: ["underwater"],
        },
        {
          shard: "insenza",
          name: "Insenza",
          date: "2022 – 2023",
          audio: "insenza.mp3",
          cover: "insenza.jpg",
          genres: ["orchestral"],
          vibes: ["sinister"],
        },
      ],
    },
  ],
};

export const albums_list: AlbumData[] = albums.pinned.concat(albums.gen1, albums.archives);
