import type { ArtistData } from "#scripts/types"


export const artists: {
  [collection: string]: ArtistData[];
} = {
  discovered: [
    {
      name: "Stessie",
      date: "2025",
      track: "What If",
      genres: ["electronic", "chill"],
      discovered: "Firefly Music",
    },
    {
      name: "Reku Mochizuki",
      date: "2025",
      track: "火",
      genres: ["electronic", "rhythm"],
      discovered: "Phigros",
    },
  ],
  favourites: [
    {
      name: "Camellia",
      date: "2023",
      track: "Dance With Silence",
      genres: ["Camelliacore", "full flavour", "transcendental", "rhythm"],
      discovered: "Phigros",
    },
    {
      name: "Vexento",
      date: "2018",
      track: "Banana Breeze",
      genres: ["electronic", "chill"],
      discovered: "Scratch",
    },
    {
      name: "PIKASONIC",
      date: "2024",
      track: "New Start",
      genres: ["electronic", "future bass", "J-core"],
      discovered: "YouTube reccs",
    },
    {
      name: "tn-shi",
      date: "2024",
      track: "Synthesis.",
      genres: ["artcore", "transcendental", "arcade"],
      discovered: "YouTube reccs",
    },
  ],
  regulars: [
    {
      name: "A-39",
      date: "2023",
      track: ["WATER", "夜"],
      genres: ["colour bass", "hardcore", "vocaloid"],
      discovered: "Phigros",
    },
    {
      name: "puru",
      date: "2024",
      track: "Grimheart",
      genres: ["rhythm", "chill", "trap"],
      discovered: "Arcaea",
    },
    {
      name: "MYUKKE.",
      date: "2023",
      track: "NO ONE YES MAN",
      genres: ["rhythm", "arcade"],
      discovered: "Phigros",
    },
    {
      name: "Silentroom",
      date: "2023",
      track: "Nhelv",
      genres: ["arcade", "neurofunk", "rhythm"],
      discovered: "YouTube",
    },
    {
      name: "Such",
      date: "2024",
      track: "Mend Your Ways",
      genres: ["J-core", "bass"],
      discovered: "YouTube Music reccs",
    },
    {
      name: "茶鸣拾贰律",
      date: "2023",
      track: ["青芽", "Feast"],
      genres: ["C-pop", "rhythm"],
      discovered: "Phigros",
    },
    {
      name: "Johannes Bornlöf",
      date: "2020",
      track: "Only the Brave",
      genres: ["cinematic", "orchestral"],
      discovered: "AirAttack 2 OST",
    },
    {
      name: "Gavin Luke",
      date: "2023",
      track: "Sentient",
      genres: ["piano", "orchestral"],
      discovered: "YouTube reccs",
    },
  ],
  mood: [
    {
      name: "Hinkik",
      date: "2024",
      track: "Realms",
      genres: ["electronic", "house"],
      discovered: "Phigros",
    },
    {
      name: "chiru-san",
      date: "2024",
      track: "Stellarity",
      genres: ["electronic", "bass"],
      discovered: "YouTube reccs",
    },
    {
      name: "RHYX",
      date: "2025",
      genres: ["hi-tech"],
      discovered: "YouTube reccs",
    },
    {
      name: "YOASOBI",
      date: "2023",
      track: "Tabun",
      genres: ["J-pop", "anime"],
      discovered: "anime",
    },
    {
      name: "Falcon Dives",
      date: "2022",
      track: "Teenage Color",
      genres: ["disco", "electronic"],
      discovered: "Grian",
    },
    {
      name: "Street",
      date: "2024",
      track: "Sakura Fubiki",
      genres: ["neurofunk", "rhythm"],
      discovered: "Arcaea",
    },
    {
      name: "Noah",
      date: "2024",
      track: "Revolt From The Abyss",
      genres: ["cinematic", "rhythm"],
      discovered: "Phigros",
    },
    {
      name: "JMT",
      date: "2023",
      track: ["inferior", "Shadow"],
      genres: ["neurofunk", "rhythm"],
      discovered: "Phigros",
    },
    {
      name: "Frums",
      date: "2024",
      track: "XNOR XNOR XNOR",
      genres: ["Frums"],
      discovered: "Phigros",
    },
    {
      name: "Virtual Riot",
      date: "2024",
      track: "I heard you like polyrhythms",
      genres: ["electronic", "complextro", "dubstep"],
      discovered: "YouTube reccs",
    },
    {
      name: "heiakim",
      date: "2024",
      track: "nana",
      genres: ["J-pop"],
      discovered: "YouTube reccs",
    },
    {
      name: "Tanger",
      date: "2024",
      track: "",
      genres: ["electronic"],
      discovered: "YouTube reccs",
    },
    {
      name: "feuerrmFilms",
      date: "2018",
      track: "Special Events",
      genres: ["electronic"],
      discovered: "YouTube",
    },
    {
      name: "Bo Burnham",
      date: "2021",
      track: ["Are You Happy", "The Chicken"],
      genres: ["comedy", "pop", "rap", "piano"],
      discovered: "YouTube reccs",
    },
  ],
  classics: [
    {
      name: "Elektronomia",
      date: "2016",
      track: ["United", "Ibiza"],
      genres: ["electronic", "house"],
      discovered: "iXPLODE",
    },
    {
      name: "Alan Walker",
      date: "2018",
      track: "Different World",
      genres: ["electronic", "house"],
      discovered: "friend",
    },
    {
      name: "Jim Yosef",
      date: "2016",
      track: "Linked",
      genres: ["electronic", "house"],
      discovered: "NCS",
    },
    {
      name: "Electro-Light",
      date: "2017",
      track: "Throwback",
      genres: ["electronic", "hardcore"],
      discovered: "NCS",
    },
    {
      name: "Alex Skrindo",
      date: "2017",
      track: "Lightning",
      genres: ["electronic"],
      discovered: "NCS",
    },
    {
      name: "TheFatRat",
      date: "2019",
      track: "Monody",
      genres: ["electronic"],
      discovered: "YouTube",
    },
    {
      name: "K-391",
      date: "2019",
      track: "Lonely World",
      genres: ["electronic"],
      discovered: "Alan Walker",
    },
  ],
  ost: [
    {
      name: "Arcane",
      date: "2025",
      track: "What Could Have Been",
    },
    {
      name: "Ultraman",
      date: "2018",
      track: ["Ultraman Mebius", "Ultraman Zero"],
    },
    {
      name: "Master Duel",
      date: "2023",
    },
    {
      name: "Yu-Gi-Oh!",
      date: "2022",
      track: ["Calling", "BRAVING"],
    },
    {
      name: "AirAttack",
      date: "2020",
      track: ["Dark Sands", "Operation Red Sea – Land"],
    },
    {
      name: "Tiny Defense",
      date: "2020",
      track: ["Mission Stage", "Underwater"],
    },
    {
      name: "Plants vs. Zombies",
      date: "2020",
      track: "Zombie On Your Lawn",
    },
    {
      name: "Dune",
      date: "2022",
    },
    {
      name: "My Little Pony",
      date: "2023",
      track: ["Friendship Games", "Legend You Were Meant To Be"],
    },
  ],
  beatbox: [
    {
      name: "WING",
      date: "2025",
      track: "Dopamine (DnB remix)",
      genres: ["beatbox"],
      discovered: "YouTube",
    },
    {
      name: "KAJI",
      date: "2025",
      track: "Bass Factory",
      genres: ["beatbox", "hardcore", "techno"],
      discovered: "Grand Beatbox Battle vs WING",
    },
    {
      name: "Improver",
      date: "2025",
      track: "Feel the Future",
      genres: ["beatbox", "drum & bass"],
      discovered: "Grand Beatbox Battle vs WING",
    },
  ],
  pop: [
    {
      name: "Avril Lavigne",
      date: "2017",
      track: "When You’re Gone",
      genres: ["rock", "pop"],
      discovered: "some Ultraman video on YouTube",
    },
    {
      name: "Taylor Swift",
      track: "Anti-hero",
      genres: ["pop"],
    },
    {
      name: "Owl City",
      date: "2022",
      track: "Fireflies",
      genres: ["pop"],
      discovered: "nostalgia",
    },
  ],
  labels: [
    {
      name: "Firefly Music",
      date: "2025",
      genres: ["electronic"],
      discovered: "PIKASONIC",
    },
    {
      name: "NoCopyrightSounds",
      date: "2017",
      genres: ["electronic"],
      discovered: "iXPLODE",
    },
    {
      name: "NomiaTunes",
      genres: ["electronic"],
      discovered: "Elektronomia",
    },
  ],
  isolates: [
    {
      name: "Giga",
      date: "2024",
      track: "Beyond the Way",
      genres: ["trap", "vocaloid"],
      discovered: "YouTube reccs",
    },
    {
      name: "DECO*27",
      date: "2024",
      track: "Rabbit Hole",
      genres: ["vocaloid"],
      discovered: "YouTube reccs",
    },
    {
      name: "Lupus Nocte",
      date: "2021",
      track: "Howling",
      genres: ["electronic"],
      discovered: "GoodTimesWithScar",
    },
    {
      name: "Eason Chan",
      date: "2023",
      track: "孤勇者",
      genres: ["C-pop"],
      discovered: "friend",
    },
    {
      name: "TFBOYS",
      track: "少年修炼手册",
      genres: ["C-pop"],
      discovered: "childhood",
    },
  ],
};
