import { i } from "#scripts/utils";
import { Daw } from "#scripts/types/music/create";
import type { AlbumData, TrackData } from "#scripts/types/music/create";
import type { Groups } from "#scripts/types";


/* @ts-ignore */
export const albums_data: Groups<AlbumData> = assign_albums({
  pinned: [
    {
      shard:  "singles",
      name:   "Singles",
      cover:  "single.sunset.png",
      tracks: [
        {
          shard:  "sunrise",
          name:   "Sunrise",
          date:   ["29 October 2024", "September 2025"],
          audio:  "sunrise-preview.m4a",
          cover:  "placeholder.png",
          genres: ["electronic"],
          vibes:  ["chillout"],
        },
        {
          shard:  "gurls",
          name:   "aespa – Girls (Sup#2.0 remix)",
          date:   ["18 January 2025", "24 January 2025"],
          audio:  "gurls-p1.m4a",
          cover:  "placeholder.png",
          genres: ["neurofunk", "hardcore", "electronic"],
        },
        {
          shard:  "sunset",
          name:   "Sunset",
          date:   ["8 October 2023", "November 2023"],
          audio:  "sunset.m4a",
          cover:  "single.sunset.png",
          genres: ["electronic"],
          vibes:  ["chillout"],
        },
      ]
    },
  ],
  gen1: [
    {
      shard:  "stranded",
      name:   "Stranded",
      date:   [2025, "present"],
      cover:  "placeholder.png",
      tracks: [
        {
          shard:  "stranded",
          name:   "Stranded",
          is_preview: true,
        },
        {
          shard:  "catastropical",
          name:   "Catastropical",
          is_preview: true,
        },
        {
          shard:  "a-journey-across-time",
          name:   "A Journey Across Time",
          date:   ["13 May 2025", "September 2025"],
          audio:  "a-journey-across-time-p1.m4a",
          cover:  "placeholder.png",
          genres: ["cinematic"],
          vibes:  ["poignant"],
        },
        {
          shard:  "ever-shining",
          name:   "Ever Shining",
          is_preview: true,
        },
        {
          shard:  "requital",
          name:   "Requital",
          is_preview: true,
        },
        {
          shard:  "walkers",
          name:   "Walkers",
          is_preview: true,
        },
      ],
    },
    {
      shard:  "integral",
      name:   "Integral",
      date:   [2024, "present"],
      daw:    Daw.GarageBand,
      desc:
        `Soundtracks for nontrivial mathematical shenanigans.`,
      tracks: [
        {
          feat:   true,
          shard:  "audacious-antiderivative",
          name:   "Audacious Antiderivative",
          date:   ["20 September 2024", "present"],
          audio:  undefined,
          cover:  undefined,
          genres: ["electronic", "polymeter"],
          vibes:  ["vibrant"],
          is_preview: true,
        },
        {
          shard:  "pathological-constant",
          name:   "Pathological Constant",
          date:   ["20 September 2024", "present"],
          audio:  undefined,
          cover:  undefined,
          is_preview: true,
        },
        {
          shard:  "isomorphic-surjection",
          name:   "Isomorphic Surjection",
          audio:  undefined,
          cover:  undefined,
          is_preview: true,
        },
        {
          shard:  "subzero-abstraction",
          name:   "Subzero Abstraction",
          audio:  undefined,
          cover:  undefined,
          is_preview: true,
        },
        {
          shard:  "luminous-conjecture",
          name:   "Luminous Conjecture",
          audio:  undefined,
          cover:  undefined,
          is_preview: true,
        },
        {
          shard:  "transverse-erratum",
          name:   "Transverse Erratum",
          audio:  undefined,
          cover:  undefined,
          is_preview: true,
        },
        {
          shard:  "canonical-destruction",
          name:   "Canonical Destruction",
          audio:  undefined,
          cover:  undefined,
          is_preview: true,
        },
        {
          feat:   true,
          shard:  "infinitesimal-ignition",
          name:   "Infinitesimal Ignition",
          date:   ["16 March 2024", "present"],
          audio:  undefined,
          cover:  undefined,
          genres: ["bass"],
          is_preview: true,
        },
      ],
    },
    {
      shard:  "cortex",
      name:   "Cortex",
      date:   [2024, "present"],
      cover:  "cortex.png",
      daw:    Daw.GarageBand,
      desc:
        `Might actually be the first album I come close to finishing :0`,
      tracks: [
        {
          is_preview: true,
          shard:  "purity",
          name:   "puri:ty",
          audio:  undefined,
          cover:  undefined,
          genres: ["neurofunk"],
          vibes:  [],
        },
        {
          feat:   true,
          shard:  "voxel",
          name:   "Voxel",
          date:   ["26 June 2024", "summer 2024"],
          audio:  "voxel.m4a",
          cover:  "cortex.voxel.png",
          genres: ["electronic", "complextro", "arcade"],
          vibes:  ["bop"],
        },
        {
          shard:  "pseudorandom",
          name:   "pseudorandom",
          date:   ["15 December 2024", "September 2025"],
          audio:  "pseudorandom-preview.m4a",
          cover:  "cortex.pseudorandom.png",
          genres: ["wackcore"],
          vibes:  ["random"],
        },
        {
          shard:  "dactyl",
          name:   "Dactyl",
          date:   ["8 March 2024", "September 2025"],
          audio:  "dactyl-p1.m4a",
          cover:  "cortex.dactyl.png",
          genres: ["rhythm", "electronic", "bass"],
          vibes:  ["vibrant"],
        },
        {
          is_preview: true,
          shard:  "mem-brain",
          name:   "MEM=BRAIN",
          date:   ["24 March 2025", "present"],
          audio:  undefined,
          cover:  "cortex.mem-brain.png",
          genres: ["rhythm", "wackcore"],
          vibes:  [],
        },
        {
          shard:  "syntax-error",
          name:   "SyntaxErrør",
          date:   ["10 February 2025", "September 2025"],
          audio:  "syntax-error-p1.m4a",
          cover:  "cortex.syntax-error.png",
          genres: ["wackcore"],
          vibes:  [],
        },
        {
          shard:  "elysion",
          name:   "Π0!ZV/Σ",
          date:   ["28 June 2025", "September 2025"],
          audio:  "elysion.m4a",
          cover:  "cortex.elysion.png",
          genres: ["wackcore", "hardstyle"],
          vibes:  ["vibrant"],
        },
        {
          is_preview: true,
          feat:   true,
          shard:  "the-algorithm",
          name:   "The Algorithm",
          audio:  undefined,
          cover:  undefined,
          genres: [],
          vibes:  [],
        },
      ],
    },
    {
      shard:  "elysion",
      name:   "ELYSION",
      date:   [2023, "present"],
      cover:  "elysion.png",
      daw:    Daw.GarageBand,
      desc:
        `Experimental soundtracks in a variety of genres.`,
      tracks: [
        {
          feat:   true,
          shard:  "aphenia",
          name:   "Aphenia",
          date:   ["december 2023", "spring 2024"],
          audio:  "aphenia.m4a",
          cover:  "elysion.aphenia.png",
          genres: ["neurofunk", "ambient"],
          vibes:  ["sinister"],
        },
        {
          is_preview: true,
          shard:  "ephemerald",
          name:   "Ephemerald",
          date:   ["24 September 2024", "present"],
          audio:  undefined,
          cover:  "elysion.ephemerald.png",
          genres: ["artcore"],
          vibes:  ["poignant"],
        },
        {
          is_preview: true,
          shard:  "lullacry",
          name:   "Lullacry",
          audio:  undefined,
          cover:  undefined,
          genres: ["lo-fi"],
          vibes:  [],
        },
        {
          shard:  "ceruleus",
          name:   "Ceruleus",
          date:   ["19 May 2024", "December 2024"],
          audio:  "ceruleus.m4a",
          cover:  "elysion.ceruleus.png",
          genres: ["orchestral", "neurofunk"],
          vibes:  ["poignant"],
        },
        {
          is_preview: true,
          shard:  "archiral",
          name:   "Archiral",
          audio:  undefined,
          cover:  undefined,
          genres: [],
          vibes:  [],
        },
        {
          shard:  "viridian",
          name:   "Viridian",
          date:   ["14 July 2024", "march 2025"],
          audio:  "viridian.m4a",
          cover:  "elysion.viridian.png",
          genres: ["artcore"],
          vibes:  ["vibrant"],
        },
        {
          is_preview: true,
          feat:   true,
          shard:  "scars",
          name:   "Scars",
          audio:  undefined,
          cover:  undefined,
          genres: ["hardcore"],
          vibes:  ["melodramatic"],
        },
      ],
    },
    {
      shard:  "algo-vision",
      name:   "Algorhythm Vision",
      date:   "2024 – PRESENT",
      audio:  "another-dawn.m4a",
      cover:  "vision.another-dawn.png",
      daw:    Daw.GarageBand,
      desc:
        `New soundtracks created for the revival of my rhythm game ${i("Algorhythm")}.`,
      tracks: [
        {
          feat:   true,
          shard:  "another-dawn",
          name:   "Another Dawn",
          date:   ["21 July 2024", "summer 2024"],
          audio:  "another-dawn.m4a",
          cover:  "vision.another-dawn.png",
          genres: ["electronic"],
          vibes:  ["epic", "vibrant"],
        },
        {
          shard:  "daybreak",
          name:   "Daybreak",
          audio:  undefined,
          cover:  undefined,
          genres: ["electronic"],
          vibes:  ["vibrant"],
          is_preview: true,
        },
        {
          shard:  "nightfall",
          name:   "Nightfall",
          date:   ["24 August 2025", "April 2026"],
          audio:  "nightfall-v1.m4a",
          cover:  "vision.nightfall.png",
          genres: ["electronic"],
          vibes:  ["euphoric", "vibrant"],
        },
        {
          shard:  "reminiscence",
          name:   "Reminiscence",
          date:   ["30 August 2024", "winter 2024"],
          audio:  "reminiscence.m4a",
          cover:  "vision.reminiscence.png",
          genres: ["ambient", "lo-fi"],
          vibes:  ["muted"],
        },
        {
          is_preview: true,
          feat:   true,
          shard:  "midnight",
          name:   "Midnight",
          audio:  undefined,
          cover:  undefined,
          genres: ["electronic"],
          vibes:  [],
        },
      ],
    },
    {
      shard:  "algo-roots",
      name:   "Algorhythm Roots",
      date:   [2024, "present"],
      cover:  "roots.rush-reloaded.png",
      daw:    Daw.GarageBand,
      desc:
        `More soundtracks created for my rhythm game ${i("Algorhythm")}!`,
      tracks: [
        {
          is_preview: true,
          shard:  "away",
          name:   "Away",
          date:   ["22 October 2023", "present"],
          audio:  undefined,
          cover:  "roots.away.png",
          genres: ["wackcore"],
          vibes:  [],
        },
        {
          shard:  "rejuvenate",
          name:   "Rejuvenate",
          date:   ["7 July 2024", "fall 2024"],
          audio:  "rejuvenate-preview.m4a",
          cover:  "roots.rejuvenate.png",
          genres: ["electronic"],
          vibes:  ["jubilant"],
        },
        {
          is_preview: true,
          shard:  "drop",
          name:   "Drop",
          audio:  undefined,
          cover:  undefined,
          genres: [],
          vibes:  [],
        },
        {
          feat:   true,
          shard:  "rush-reloaded",
          name:   "Rush Reloaded",
          date:   ["5 November 2023", "summer 2025"],
          audio:  "rush-reloaded-preview.m4a",
          cover:  "roots.rush-reloaded.png",
          genres: ["rhythm", "arcade"],
          vibes:  ["intense"],
        },
        {
          shard:  "skies-above",
          name:   "Skies Above",
          date:   ["january 2026"],
          audio:  undefined,
          cover:  "roots.skies-above.png",
          genres: ["electronic"],
          vibes:  ["chillout"],
        },
        {
          is_preview: true,
          feat:   true,
          shard:  "rise",
          name:   "Rise",
          date:   ["18 September 2023", "present"],
          audio:  undefined,
          cover:  undefined,
          genres: ["artcore", "hardcore"],
          vibes:  ["melodramatic"],
        },
      ],
    },
    {
      shard:  "algo-origins",
      name:   "Algorhythm Origins",
      date:   [2023, "present"],
      cover:  "origins.night.png",
      daw:    Daw.GarageBand,
      desc:
        `Soundtracks created for my rhythm game ${i("Algorhythm")}!`,
      tracks: [
        {
          shard:  "dawn",
          name:   "Dawn",
          date:   ["september 2023"],
          audio:  "dawn.m4a",
          cover:  "origins.dawn.png",
          genres: ["electronic"],
          vibes:  ["muted", "chill"],
        },
        {
          shard:  "day",
          name:   "Day",
          date:   ["october 2023"],
          audio:  "day.m4a",
          cover:  "origins.day.png",
          genres: ["electronic"],
          vibes:  ["vibrant"],
        },
        {
          feat:   true,
          shard:  "night",
          name:   "Night",
          date:   "october 2023",
          audio:  "night.m4a",
          cover:  "origins.night.png",
          genres: ["electronic"],
          vibes:  ["vibrant"],
        },
        {
          shard:  "yesterday",
          name:   "Yesterday",
          audio:  undefined,
          cover:  undefined,
          genres: ["electronic"],
          vibes:  [],
          is_preview: true,
        },
        {
          shard:  "tomorrow",
          name:   "Tomorrow",
          date:   ["14 October 2023", "January 2024"],
          audio:  "tomorrow.m4a",
          cover:  "origins.tomorrow.png",
          genres: ["electronic"],
          vibes:  ["jubilant"],
        },
        {
          is_preview: true,
          shard:  "dusk",
          name:   "Dusk",
          audio:  undefined,
          genres: ["electronic"],
          vibes:  [],
        },
        {
          is_preview: true,
          feat:   true,
          shard:  "time",
          name:   "Time",
          audio:  undefined,
          genres: ["electronic"],
          vibes:  [],
        },
        {
          is_preview: true,
          shard:  "twilight",
          name:   "Twilight",
          audio:  undefined,
          genres: ["electronic"],
          vibes:  [],
        },
      ],
    },
  ],
  future: [
    {
      shard:  "affinity",
      name:   "Affinity",
      date:   "FUTURE",
      is_preview: true,
      tracks: [
        {
          shard:  "solitude",
          name:   "solitude",
          is_preview: true,
        },
        {
          shard:  "pinpricks",
          name:   "pinpricks",
          is_preview: true,
        },
        {
          shard:  "forest-foliage",
          name:   "forest-foliage",
          is_preview: true,
        },
        {
          shard:  "close-to-earth",
          name:   "close-to-earth",
          is_preview: true,
        },
        {
          shard:  "midnight-marauder",
          name:   "midnight-marauder",
          is_preview: true,
        },
        {
          shard:  "night-dweller",
          name:   "night-dweller",
          is_preview: true,
        },
        {
          shard:  "droplets",
          name:   "droplets",
          is_preview: true,
        },
        {
          shard:  "blinded-by-water",
          name:   "blinded-by-water",
          is_preview: true,
        },
        {
          shard:  "cloudjumper",
          name:   "cloudjumper",
          is_preview: true,
        },
      ],
    },
    {
      shard:  "fidelity",
      name:   "Fidelity",
      date:   "FUTURE",
      is_preview: true,
      tracks: [
        {
          shard:  "our-time",
          name:   "our-time",
          is_preview: true,
        },
        {
          shard:  "a-place-far-away",
          name:   "a-place-far-away",
          is_preview: true,
        },
        {
          shard:  "whisper",
          name:   "whisper",
          is_preview: true,
        },
        {
          shard:  "lost-in-your-eyes",
          name:   "lost-in-your-eyes",
          is_preview: true,
        },
        {
          shard:  "intrepid",
          name:   "intrepid",
          is_preview: true,
        },
        {
          shard:  "a-time-long-ago",
          name:   "a-time-long-ago",
          is_preview: true,
        },
        {
          shard:  "our-story",
          name:   "our-story",
          is_preview: true,
        },
      ],
    },
  ],
  archives: [
    {
      shard:  "garageband",
      name:   "GarageBand Archives",
      date:   [2024, "earlier"],
      cover:  "garageband.jpg",
      daw:    Daw.GarageBand,
      desc:
        `Miscellaneous and ancient creations in GarageBand.`,
      tracks: [
        {
          shard:  "let-you-down",
          name:   "Let You Down",
          date:   "spring 2024",
          audio:  "let-you-down.m4a",
          cover:  "let-you-down.jpg",
          vibes:  ["chill", "jokes"],
        },
        {
          shard:  "canon-in-d-remix",
          name:   "Canon in D (remix)",
          date:   "2019",
          audio:  "canon-in-d-remix.m4a",
          cover:  "placeholder.png",
          genres: ["orchestral", "electronic"],
        },
        {
          shard:  "rush",
          name:   "Rush",
          date:   "2019",
          audio:  undefined,
          cover:  "placeholder.png",
          genres: ["bass"],
          vibes:  ["experimental"],
        },
        {
          feat:   true,
          shard:  "base-memories",
          name:   "Base Memories",
          date:   "2019",
          audio:  undefined,  // FIXME
          cover:  "placeholder.png",
          genres: ["bass"],
          vibes:  ["muted", "experimental"],
        },
      ],
    },
    {
      shard:  "musescore",
      name:   "MuseScore Archives",
      date:   "2023 – EARLIER",
      cover:  "musescore.png",
      daw:    Daw.MuseScore,
      desc:
        `Piano and orchestral compositions from MuseScore`,
      tracks: [
        {
          feat:   true,
          shard:  "wingless-butterfly",
          name:   "The Wingless Fire-Wielding Butterfly Who Waged War Upon the Forest",
          date:   "2023 WINTER",
          audio:  "wingless-butterfly.mp3",
          cover:  "placeholder.png",
          genres: ["piano"],
          vibes:  ["jokes"],
        },
        {
          shard:  "bubble-iris",
          name:   "Bubble Iris",
          date:   "2023",
          audio:  "bubble-iris.mp3",
          cover:  "bubble-iris.jpg",
          genres: ["orchestral", "cinematic"],
          vibes:  ["underwater"],
        },
        {
          shard:  "insenza",
          name:   "Insenza",
          date:   "2022 – 2023",
          audio:  "insenza.mp3",
          cover:  "insenza.jpg",
          genres: ["orchestral"],
          vibes:  ["sinister"],
        },
      ],
    },
  ],
} as Groups<AlbumData>);

export const albums_list: AlbumData[] = Object.values(albums_data).flat();

export const tracks_list: TrackData[] = Object.values(albums_data).flatMap(
  collection => collection.flatMap(
    album => album.tracks
  )
);


function assign_albums(album_data: object)
{
  for (let collection of Object.values(album_data)) {
    for (let album of collection) {
      for (let track of album.tracks) {
        track.album = album;
        track._score = 0;
      }
    }
  }

  return album_data;
}
