import { i } from "#scripts/utils";
import { Daw } from "#scripts/types";
import type { AlbumData, TrackData } from "#scripts/types";


/* @ts-ignore */
export const albums_data: {
  [series: string]: AlbumData[]
} = assign_albums({
  pinned: [
    {
      shard: "singles",
      name: "Singles",
      cover: "sunset.png",
      tracks: [
        {
          shard: "sunset",
          name: "Sunset",
          audio: "sunset.m4a",
          cover: "sunset.png",
          genres: ["electronic"],
          vibes: ["chillout"],
        },
        {
          feat: true,
          shard: "sunrise",
          name: "Sunrise",
          audio: "sunrise-preview.m4a",
          cover: "placeholder.png",
          genres: ["electronic"],
          vibes: ["chillout"],
        },
        {
          shard: "gurls",
          name: "aespa – Girls (Sup#2.0 remix)",
          audio: "gurls-p1.m4a",
          cover: "placeholder.png",
          genres: ["neurofunk", "hardcore", "electronic"],
        }
      ]
    },
  ],
  gen1: [
    {
      shard: "algo-origins",
      name: "Algorhythm Origins",
      date: "2023 – PRESENT",
      cover: "origins.night.png",
      daw: Daw.GarageBand,
      desc: `Soundtracks created for my rhythm game ${i("Algorhythm")}!`,
      tracks: [
        {
          shard: "dawn",
          name: "Dawn",
          audio: "dawn.m4a",
          cover: "origins.dawn.png",
          genres: ["electronic"],
          vibes: ["muted", "chill"],
        },
        {
          shard: "day",
          name: "Day",
          audio: "day.m4a",
          cover: "origins.day.png",
          genres: ["electronic"],
          vibes: ["vibrant"],
        },
        {
          feat: true,
          shard: "night",
          name: "Night",
          audio: "night.m4a",
          cover: "origins.night.png",
          genres: ["electronic"],
          vibes: ["vibrant"],
        },
        {
          shard: "yesterday",
          name: "Yesterday",
          audio: "yesterday.m4a",
          cover: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "tomorrow",
          name: "Tomorrow",
          audio: "tomorrow.m4a",
          cover: "origins.tomorrow.png",
          genres: ["electronic"],
          vibes: ["jubilant"],
        },
        {
          shard: "dusk",
          name: "Dusk",
          audio: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
        {
          feat: true,
          shard: "time",
          name: "Time",
          audio: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "twilight",
          name: "Twilight",
          audio: "twilight.m4a",
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
      ],
    },
    {
      shard: "algo-roots",
      name: "Algorhythm Roots",
      date: "2024 – PRESENT",
      cover: "roots.rush-reloaded.png",
      daw: Daw.GarageBand,
      desc: `More soundtracks created for my rhythm game ${i("Algorhythm")}!`,
      tracks: [
        {
          shard: "away",
          name: "Away",
          audio: undefined,
          cover: undefined,
          genres: ["wackcore"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "rejuvenate",
          name: "Rejuvenate",
          audio: "rejuvenate-preview.m4a",
          cover: "placeholder.png",
          genres: ["electronic"],
          vibes: ["jubilant"],
        },
        {
          shard: "drop",
          name: "Drop",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          feat: true,
          shard: "rush-reloaded",
          name: "Rush Reloaded",
          audio: "rush-reloaded-preview.m4a",
          cover: "roots.rush-reloaded.png",
          genres: ["rhythm", "arcade"],
          vibes: ["intense"],
        },
        {
          feat: true,
          shard: "rise",
          name: "Rise",
          audio: undefined,
          cover: undefined,
          genres: ["artcore", "hardcore"],
          vibes: ["melodramatic"],
          is_preview: true,
        },
      ],
    },
    {
      shard: "algo-vision",
      name: "Algorhythm Vision",
      date: "2024 – PRESENT",
      audio: "another-dawn.m4a",
      cover: "vision.another-dawn.png",
      daw: Daw.GarageBand,
      desc: `New soundtracks created for the revival of my rhythm game ${i("Algorhythm")}.`,
      tracks: [
        {
          feat: true,
          shard: "another-dawn",
          name: "Another Dawn",
          audio: "another-dawn.m4a",
          cover: "vision.another-dawn.png",
          genres: ["electronic"],
          vibes: ["epic", "vibrant"],
        },
        {
          shard: "daybreak",
          name: "Daybreak",
          audio: undefined,
          cover: undefined,
          genres: ["electronic"],
          vibes: ["vibrant"],
          is_preview: true,
        },
        {
          shard: "nightfall",
          name: "Nightfall",
          audio: undefined,
          cover: undefined,
          genres: ["electronic"],
          vibes: ["euphoric", "vibrant"],
          is_preview: true,
        },
        {
          shard: "reminiscence",
          name: "Reminiscence",
          audio: "reminiscence.m4a",
          cover: "vision.reminiscence.png",
          genres: ["ambient", "lo-fi"],
          vibes: ["muted"],
        },
        {
          feat: true,
          shard: "midnight",
          name: "Midnight",
          audio: undefined,
          cover: undefined,
          genres: ["electronic"],
          vibes: [],
          is_preview: true,
        },
      ],
    },
    {
      shard: "elysion",
      name: "ELYSION",
      date: "2023 – PRESENT",
      cover: "elysion.png",
      daw: Daw.GarageBand,
      desc: `Experimental soundtracks in a variety of genres.`,
      tracks: [
        {
          feat: true,
          shard: "aphenia",
          name: "Aphenia",
          audio: "aphenia.m4a",
          cover: "elysion.aphenia.png",
          genres: ["neurofunk", "ambient"],
          vibes: ["sinister"],
        },
        {
          shard: "ephemerald",
          name: "Ephemerald",
          audio: undefined,
          cover: "elysion.ephemerald.png",
          genres: ["artcore"],
          vibes: ["poignant"],
          is_preview: true,
        },
        {
          shard: "lullacry",
          name: "Lullacry",
          audio: undefined,
          cover: undefined,
          genres: ["lo-fi"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "ceruleus",
          name: "Ceruleus",
          audio: "ceruleus.m4a",
          cover: "elysion.ceruleus.png",
          genres: ["orchestral", "neurofunk"],
          vibes: ["poignant"],
        },
        {
          shard: "archiral",
          name: "Archiral",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "viridian",
          name: "Viridian",
          audio: "viridian.m4a",
          cover: "elysion.viridian.png",
          genres: ["artcore"],
          vibes: ["vibrant"],
        },
        {
          feat: true,
          shard: "scars",
          name: "Scars",
          audio: undefined,
          cover: undefined,
          genres: ["hardcore"],
          vibes: ["melodramatic"],
          is_preview: true,
        },
      ],
    },
    {
      shard: "cortex",
      name: "Cortex",
      date: "2024 – PRESENT",
      cover: "cortex.png",
      daw: Daw.GarageBand,
      desc: `Techy!`,
      tracks: [
        {
          shard: "purity",
          name: "puri:ty",
          audio: undefined,
          cover: undefined,
          genres: ["neurofunk"],
          vibes: [],
          is_preview: true,
        },
        {
          feat: true,
          shard: "voxel",
          name: "Voxel",
          audio: "voxel.m4a",
          cover: "cortex.voxel.png",
          genres: ["electronic", "complextro", "arcade"],
          vibes: ["bop"],
        },
        {
          shard: "pseudorandom",
          name: "pseudorandom",
          audio: "pseudorandom-preview.m4a",
          cover: "cortex.pseudorandom.png",
          genres: ["wackcore"],
          vibes: ["random"],
        },
        {
          shard: "dactyl",
          name: "Dactyl",
          audio: "dactyl-p1.m4a",
          cover: "cortex.dactyl.png",
          genres: ["rhythm", "electronic", "bass"],
          vibes: ["vibrant"],
        },
        {
          shard: "mem-brain",
          name: "MEM=BRAIN",
          audio: undefined,
          cover: "cortex.mem-brain.png",
          genres: ["rhythm", "wackcore"],
          vibes: [],
          is_preview: true,
        },
        {
          shard: "syntax-error",
          name: "SyntaxError",
          audio: "syntax-error-p1.m4a",
          cover: "cortex.syntax-error.png",
          genres: ["wackcore"],
          vibes: [],
        },
        {
          shard: "elysion",
          name: "Π0!ZV/Σ",
          audio: "elysion.m4a",
          cover: "cortex.elysion.png",
          genres: ["wackcore", "hardstyle"],
          vibes: ["vibrant"],
        },
        {
          feat: true,
          shard: "the-algorithm",
          name: "The Algorithm",
          audio: undefined,
          cover: undefined,
          genres: [],
          vibes: [],
          is_preview: true,
        },
      ],
    },
    {
      shard: "integral",
      name: "Integral",
      date: "2024 – PRESENT",
      daw: Daw.GarageBand,
      desc: "Soundtracks for nontrivial mathematical shenanigans.",
      tracks: [
        {
          feat: true,
          shard: "audacious-antiderivative",
          name: "Audacious Antiderivative",
          audio: undefined,
          cover: undefined,
          genres: ["electronic", "polymeter"],
          vibes: ["vibrant"],
          is_preview: true,
        },
        {
          shard: "pathological-constant",
          name: "Pathological Constant",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "isomorphic-surjection",
          name: "Isomorphic Surjection",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "subzero-abstraction",
          name: "Subzero Abstraction",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "luminous-conjecture",
          name: "Luminous Conjecture",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "transverse-erratum",
          name: "Transverse Erratum",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          shard: "canonical-destruction",
          name: "Canonical Destruction",
          audio: undefined,
          cover: undefined,
          is_preview: true,
        },
        {
          feat: true,
          shard: "infinitesimal-ignition",
          name: "Infinitesimal Ignition",
          audio: undefined,
          cover: undefined,
          genres: ["bass"],
          is_preview: true,
        },
      ],
    },
    {
      shard: "affinity",
      name: "Affinity",
      date: "FUTURE",
      is_preview: true,
      tracks: [
        {
          shard: "solitude",
          name: "solitude",
          is_preview: true,
        },
        {
          shard: "pinpricks",
          name: "pinpricks",
          is_preview: true,
        },
        {
          shard: "forest-foliage",
          name: "forest-foliage",
          is_preview: true,
        },
        {
          shard: "close-to-earth",
          name: "close-to-earth",
          is_preview: true,
        },
        {
          shard: "midnight-marauder",
          name: "midnight-marauder",
          is_preview: true,
        },
        {
          shard: "night-dweller",
          name: "night-dweller",
          is_preview: true,
        },
        {
          shard: "droplets",
          name: "droplets",
          is_preview: true,
        },
        {
          shard: "blinded-by-water",
          name: "blinded-by-water",
          is_preview: true,
        },
        {
          shard: "cloudjumper",
          name: "cloudjumper",
          is_preview: true,
        },
      ],
    },
    {
      shard: "fidelity",
      name: "Fidelity",
      date: "FUTURE",
      is_preview: true,
      tracks: [
        {
          shard: "our-time",
          name: "our-time",
          is_preview: true,
        },
        {
          shard: "a-place-far-away",
          name: "a-place-far-away",
          is_preview: true,
        },
        {
          shard: "whisper",
          name: "whisper",
          is_preview: true,
        },
        {
          shard: "lost-in-your-eyes",
          name: "lost-in-your-eyes",
          is_preview: true,
        },
        {
          shard: "intrepid",
          name: "intrepid",
          is_preview: true,
        },
        {
          shard: "a-time-long-ago",
          name: "a-time-long-ago",
          is_preview: true,
        },
        {
          shard: "our-story",
          name: "our-story",
          is_preview: true,
        },
      ],
    },
    {
      shard: "stranded",
      name: "Stranded",
      date: "2025 – PRESENT",
      cover: "placeholder.png",
      tracks: [
        {
          shard: "stranded",
          name: "Stranded",
          is_preview: true,
        },
        {
          shard: "catastropical",
          name: "Catastropical",
          is_preview: true,
        },
        {
          shard: "a-journey-across-time",
          name: "A Journey Across Time",
          audio: "a-journey-across-time-p1.m4a",
          cover: "placeholder.png",
          genres: ["cinematic"],
          vibes: ["poignant"],
        },
        {
          shard: "ever-shining",
          name: "Ever Shining",
          is_preview: true,
        },
        {
          shard: "requital",
          name: "Requital",
          is_preview: true,
        },
        {
          shard: "walkers",
          name: "Walkers",
          is_preview: true,
        },
      ],
    },
  ],
  archives: [
    {
      shard: "garageband",
      name: "GarageBand Archives",
      date: "2024 – EARLIER",
      cover: "garageband.jpg",
      daw: Daw.GarageBand,
      desc: `Miscellaneous and ancient creations in GarageBand.`,
      tracks: [
        {
          shard: "let-you-down",
          name: "Let You Down",
          date: "2024 SPRING",
          audio: "let-you-down.m4a",
          cover: "placeholder.png",
          vibes: ["chill", "jokes"],
        },
        {
          shard: "canon-in-d-remix",
          name: "Canon in D (remix)",
          date: "2019",
          audio: "canon-in-d-remix.m4a",
          cover: "placeholder.png",
          genres: ["orchestral", "electronic"],
        },
        {
          shard: "rush",
          name: "Rush",
          date: "2019",
          audio: "rush.m4a",
          cover: "placeholder.png",
          genres: ["bass"],
          vibes: ["experimental"],
        },
        {
          feat: true,
          shard: "base-memories",
          name: "Base Memories",
          date: "2019",
          audio: "base-memories.m4a",
          cover: "placeholder.png",
          genres: ["bass"],
          vibes: ["muted", "experimental"],
        },
      ],
    },
    {
      shard: "musescore",
      name: "MuseScore Archives",
      date: "2023 – EARLIER",
      cover: "musescore.png",
      daw: Daw.MuseScore,
      desc: `Piano and orchestral compositions from MuseScore`,
      tracks: [
        {
          feat: true,
          shard: "wingless-butterfly",
          name: "The Wingless Fire-Wielding Butterfly Who Waged War Upon the Forest",
          date: "2023 WINTER",
          audio: "wingless-butterfly.mp3",
          cover: "placeholder.png",
          genres: ["piano"],
          vibes: ["jokes"],
        },
        {
          shard: "bubble-iris",
          name: "Bubble Iris",
          date: "2023",
          audio: "bubble-iris.mp3",
          cover: "bubble-iris.jpg",
          genres: ["orchestral", "cinematic"],
          vibes: ["underwater"],
        },
        {
          shard: "insenza",
          name: "Insenza",
          date: "2022 – 2023",
          audio: "insenza.mp3",
          cover: "insenza.jpg",
          genres: ["orchestral"],
          vibes: ["sinister"],
        },
      ],
    },
  ],
});

export const albums_list: AlbumData[] = Object.values(albums_data).flatMap(collection => collection);

export const tracks_list: TrackData[] = Object.values(albums_data).flatMap(
  collection => collection.flatMap(
    album => album.tracks
  )
);


function assign_albums(album_data: object)
{
  for (let collection of Object.values(album_data)) {
    for (let album of collection) {
      for (let track of album.tracks) {
        track.album = album;
        track._score_ = 0;
      }
    }
  }

  return album_data;
}
