export enum GenreKind {
  GENRE = "genre",
  VIBE  = "vibe",
}

export enum Genre {
  STEP200            = "200step",
  ALT_POP            = "alternative pop",
  ALT_PUNK_ROCK      = "alternative punk rock",
  ANIME              = "anime",
  ARCADE             = "arcade",
  ARTCORE            = "artcore",
  BASS               = "bass",
  BEATBOX            = "beatbox",
  BOSS_MUSIC         = "boss music",
  BREAKCORE          = "breakcore",
  CAMELLIACORE       = "Camelliacore",
  CINEMATIC          = "cinematic",
  COLOUR_BASS        = "colour bass",
  COMEDY             = "comedy",
  COMPLEXTRO         = "complextro",
  CPOP               = "c-pop",
  DOWNTEMPO          = "downtempo",
  DRUM_N_BASS        = "drum & bass",
  DUBSTEP            = "dubstep",
  EDM                = "EDM",
  ELECTRONIC         = "electronic",
  FULL_FLAVOUR       = "full flavour",
  FUTURE_BASS        = "future bass",
  FUTURE_CORE        = "future core",
  GAME               = "game",
  GOTHIC_HARDCORE    = "gothic hardcore",
  GUITAR             = "guitar",
  HARDCORE           = "hardcore",
  HITECH             = "hi-tech",
  HOUSE              = "house",
  JCORE              = "j-core",
  JPOP               = "k-pop",
  KAWAII             = "kawaii",
  KAWAII_FUTURE_BASS = "kawaii future bass",
  KPOP               = "k-pop",
  LOFI               = "lo-fi",
  MUSIC              = "music",
  NEUROFUNK          = "neurofunk",
  ORCHESTRAL         = "orchestral",
  ORIENTAL           = "oriental",
  PIANO              = "piano",
  POP                = "pop",
  PUNK               = "punk",
  RAP                = "rap",
  RHYTHM             = "rhythm",
  ROCK               = "rock",
  SPEEDCORE          = "speedcore",
  TECHNO             = "techno",
  TRANCE             = "trance",
  TRANSCENDENTAL     = "transcendental",
  TRAP               = "trap",
  VOCALOID           = "vocaloid",
}

export enum Vibe {
  CHILLOUT  = "chillout",
  DISCO     = "disco",
  EMOTIONAL = "emotional",
  HAPPY     = "happy",
  HEROIC    = "heroic",
  NOSTALGIC = "nostalgic",
  WAR       = "war",
}
