name: 'deploy'

on:
  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/deploy.yaml'
      - 'package-lock.json'
      - '**/new.*.svelte'
  
  schedule:
    - cron: '20 4 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
        with:
          submodules: true
          token: ${{ secrets.SUPPETY_PAT }}

      - name: '› npm audit'
        run: |
          npm audit --audit-level=moderate

      - name: 'Setup Node'
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: 'npm'

      - name: '› npm ci'
        run: |
          npm ci

      - name: '› npm run build'
        env:
          BASE_PATH: '/${{ github.event.repository.name }}/site'
        run: |
          npm run build

      - name: 'Upload Pages Artifact'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'Deploy Pages'
        id: deployment
        uses: actions/deploy-pages@v5
